name: Build and Publish Mobile-FFmpeg

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y automake autoconf build-essential pkg-config libtool nasm yasm meson ninja-build

      - name: Initialize Git Submodules
        run: |
          git submodule update --init --recursive

      - name: Build Mobile-FFmpeg
        run: |
          chmod +x android.sh
          ./android.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-ffmpeg-android
          path: prebuilt
