name: Build and Publish Mobile-FFmpeg

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y automake autoconf build-essential pkg-config libtool nasm yasm meson
          sudo apt install -y ninja-build || sudo apt install -y ninja

      - name: Build Mobile-FFmpeg
        run: |
          ./android.sh --lts --disable-x264 --disable-x265

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-ffmpeg-android
          path: prebuilt
