name: Build and Publish Mobile-FFmpeg

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y automake autoconf build-essential pkg-config libtool nasm yasm meson ninja-build \
          curl wget unzip cmake python3 python3-pip

      - name: Install Android SDK & NDK
        run: |
          sudo apt install -y android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/ndk/21.4.7075529:$PATH" >> $GITHUB_ENV
          
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d .
          mv cmdline-tools latest
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529" "cmake;3.18.1" --sdk_root=$ANDROID_HOME

      - name: Reinitialize Git Submodules (FFmpeg required)
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Install Android NDK Toolchain
        run: |
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

          

      - name: Build Mobile-FFmpeg
        run: |
          chmod +x android.sh
          ./android.sh

      - name: Upload Build Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-ffmpeg-android
          path: prebuilt
